---
name: docker-build

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
        default: "${{ github.sha }}"

env:
  TAG: ${{ inputs.tag }}

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push development docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}
          cache-from: type=gha,scope=osis
          cache-to: type=gha,mode=max,scope=osis
