---
name: release

on:
  push:
    branches-ignore:
      - development/**
      - main/**
      - q/*/**

jobs:
  docker-build:
    name: Docker image
    uses: ./.github/workflows/docker-build.yml
    with:
      namespace: osis
      tag: 0.0.3
    secrets:
      REGISTRY_LOGIN: ${{ secrets.REGISTRY_LOGIN }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  github-release:
    name: Creating GitHub Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - docker-build
    steps:
      - name: Github Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release 0.0.3
          tag_name: 0.0.3
          generate_release_notes: true
          target_commitish: ${{ github.sha }}

  gradle_build_and_upload:
    name: Gradle build and upload release
    uses: ./.github/workflows/gradle-build-and-upload.yml
    secrets: inherit
    with:
      release: true
