name: test-and-build

on:
  push:
    branches-ignore:
      - development/**
      - main/**
      - q/*/**

jobs:
  docker-build:
    name: Development docker image
    uses: ./.github/workflows/docker-build.yml

  code_coverage:
    name: code coverage
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          name: codecov-osis
