name: test-and-build

on:
  push:
    branches-ignore:
      - development/**
      - q/*/**

jobs:
  gradle_build_and_upload:
    name: Gradle build and upload snapshot
    uses: ./.github/workflows/gradle-build-and-upload.yml
    secrets: inherit

  docker-build:
    name: Development docker image
    uses: ./.github/workflows/docker-build.yml
    secrets:
      REGISTRY_LOGIN: ${{ secrets.REGISTRY_LOGIN }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  code_coverage:
    name: code coverage
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          name: codecov-osis
