name: tests

on:
  push:
    branches-ignore:
      - development/**
      - q/*/**

jobs:
  gradle_build_and_code_coverage:
    name: Gradle build and code coverage
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
      NEXUS_UNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PWD: ${{ secrets.NEXUS_PASSWORD }}
      SIGNING_KEYID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PWD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "8"
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.7.1

      - name: Gradle build
        run: gradle build

      - name: Get achieve upload signing key
        run: echo "$SIGNING_KEY" | base64 --decode > $GITHUB_WORKSPACE/secring.gpg

      - name: Gradle Upload Archives
        run: gradle uploadArchives -Psigning.secretKeyRingFile=$GITHUB_WORKSPACE/secring.gpg -PnexusUsername=$NEXUS_UNAME -PnexusPassword=$NEXUS_PWD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PWD

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          name: codecov-osis
          fail_ci_if_error: true

  docker-build:
    uses: ./.github/workflows/docker-build.yml
    secrets:
      REGISTRY_LOGIN: ${{ secrets.REGISTRY_LOGIN }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
